### ISSUE TITLE
Add workflow rules for running G123 and IHS GWSS

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#33]
Currently for H12 we have a dedicated notebook and a task in the workflow to run the GWSS for all contigs and cohorts.

However, we don't have equivalent tasks for G123 or IHS.

Later, when building the cohort pages, IHS and G123 scans get run because they are requested when building the plots. This is OK, but it might be nice to have dedicated tasks so we can see when those scans are actually being run during a snakemake build.

**Comment by sanjaynagi** [comment]
Closed with #44
