### ISSUE TITLE
Add G123 window size calibration

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#34]
Currently the size runs G123 GWSS using the window size chosen from H12 calibration. However, the G123 calibration curves generally look a bit different, and indicate a different window size should be used for G123. Suggest to add a separate G123 window size calibration step to the workflow. 

Btw, it's probably safe to assume that if a cohort passes H12 calibration then it will also pass G123 calibration, and therefore filtering of final cohorts may still only need to inspect the results of H12 calibration. Something to consider though, as there could be an edge case where H12 calibration passes but G123 calibration fails, in which case the build would break.

**Comment by sanjaynagi** [comment]
closed with #44
