### ISSUE TITLE
Run a first build for all of Ag3.0

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#42]
Run a first build of the site for all samples in Ag3.0 and all chromosomes.

**Comment by sanjaynagi** [comment]
Just done this for the entire ag3, it seems there are currently no other errors apart from #55 (fixed) and #56 (will make PR now)

**Comment by alimanfoo** [comment]
Nice one @sanjaynagi. I think I'll close this issue, but I'll leave #45 open to do the final deployment after all other issues in the milestone are resolved.
