### ISSUE TITLE
Error in `fit_exponential_peak()` in CD-NU_Gbadolite_gamb_2015_Q3-3RL H12-signal-detection

### ISSUE THREAD

**Issue by sanjaynagi** [anopheles-genomic-surveillance/selection-atlas#55]
The offending line:

`loc_max = np.argmax(y_peak1)`

- Potentially occurs when there are no signals found.

**Comment by alimanfoo** [comment]
Thanks @sanjaynagi, I can take a look.

**Comment by sanjaynagi** [comment]
Thanks @alimanfoo was planning to look today but haven't got around to it yet!

**Comment by alimanfoo** [comment]
No worries, ditto! Whoever gets to it first then... 🙂

**Comment by sanjaynagi** [comment]
Dug down a little bit - 

I noticed that the 'center' at which the `fit_exponential_peak()` function fails at in this cohort (around 38Mb) was also near where it looked like the hampel filter had removed outliers. Indeed, using the non-filtered H12 values results in the function running successfully. This seems a bit weird, because the filter replaces values rather than removing them completely...

**Comment by sanjaynagi** [comment]
With the non hampel filtered h12 values, this `if peak_delta_i > min_delta_aic and peak_in_scan_interval` condition is never satisfied, I assume because the delta_i is not above the minumm required delta_aic. So the function keeps running and is fine.

**Comment by sanjaynagi** [comment]
I think this occurs because the start and stop of the signal at indicating the same H12 window. Could be wrong. 

For now, we can ignore these rogue sites by checking for an empty list after slicing, and returning the function early, like the following

```
  if not list(y_peak1):
      return
```

But Im not sure what the expected behaviour is. Probably good if you can take a look @alimanfoo  :)

**Comment by sanjaynagi** [comment]
Worth noting too that the putative signal at 38Mb is absolutely miniscule, about peak H12=0.016.....

**Comment by alimanfoo** [comment]
Thanks Sanj for digging on this one, v useful info. Interesting edge case, not sure why this is happening. I'll take a look asap.
