### ISSUE TITLE
Dodgy signals

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#58]
I'm seeing a few dodgy looking signals, inferred where there is no sign of a peak. E.g.:

![image](https://github.com/anopheles-genomic-surveillance/selection-atlas/assets/703554/eaee9872-5252-4296-aa69-aea7a5646e14)

**Comment by alimanfoo** [comment]
Here's another one...

![image](https://github.com/anopheles-genomic-surveillance/selection-atlas/assets/703554/99780a84-fd70-4ce6-a3a1-b8d2ab58bd9f)

**Comment by alimanfoo** [comment]
I'll have a look into this one...

**Comment by sanjaynagi** [comment]
There seems to be quite a lot of these @alimanfoo ....

Any idea why the signal detection algorithm would have got worse? ....

**Comment by sanjaynagi** [comment]
![image](https://github.com/anopheles-genomic-surveillance/selection-atlas/assets/34922269/77c5098a-24ec-4b11-81bc-33f169623e4d)
60-85 Mb  

---

Uncalled signal on the left looks more real than called one on the right:
![image](https://github.com/anopheles-genomic-surveillance/selection-atlas/assets/34922269/e8ef9e13-e043-4806-b3a9-59cbfaa21d30)

---

I've seen a couple like this...?

![image](https://github.com/anopheles-genomic-surveillance/selection-atlas/assets/34922269/3fa0d03e-d423-4fbc-a495-b054671080ab)
