### ISSUE TITLE
Country pages and home page, use representative point for markers in cohort maps

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#6]
In the map on the home page and the maps in the country pages, use the representative points for plotting markers, which should then bring together all cohorts which share a common admin2 unit.

I.e., there should be exactly one marker for each admin2 unit.

**Comment by alimanfoo** [comment]
E.g., this should be just one marker...

![image](https://user-images.githubusercontent.com/703554/228223323-19fd0c44-966d-4b03-bb51-70334bc47a57.png)

**Comment by sanjaynagi** [comment]
And make it easy to differentiate between individual markers on the cohort pages and cohort markers on the home page / country page
