### ISSUE TITLE
Fix overview plots in chromosome pages

### ISSUE THREAD

**Issue by alimanfoo** [anopheles-genomic-surveillance/selection-atlas#67]
Currently the overview plots showing all the signals on the chromosome pages don't seem to be working.

When we have got them working, do any visual styling and tweaking required so they work OK with the numbers of signals we're getting from the full Ag3.0 build.

**Comment by sanjaynagi** [comment]
This seems to be an issue with fig.patches(). Not sure why its preventing the plot from being displayed though. might try and use a different glyph is possible.

**Comment by sanjaynagi** [comment]
Seems to be an issue with the 'color' property. Currently it is set to the 'color' column of ColumnDataSource. If i change the color to something like 'grey', the plot renders fine. investigating

**Comment by sanjaynagi** [comment]
Resolved! There was NaNs in the color column due to the presence of GCX1. woops. 

Set all NaNs (species not in main three) to be grey, to accommodate any other cryptic species in the data.

**Comment by sanjaynagi** [comment]
Resolved with #73
